import '@/styles/globals.scss'
import { Geist, Geist_Mono } from 'next/font/google'

import { SwrProvider } from '@/src/provider/swr-provider'

import type { Metadata } from 'next'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
	display: 'swap',
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function DefaultLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang="ja"
			suppressHydrationWarning={
				process.env.NEXT_PUBLIC_IS_HYDRATED_CHROME_APP === 'true'
			}
		>
			<head />
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<SwrProvider>{children}</SwrProvider>
			</body>
		</html>
	)
}
